#database
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

#kafka server port
spring.kafka.bootstrap-servers=host.docker.internal:9092