#tomcat port
server.port=8083

#config for spring data jpa
spring.datasource.url=jdbc:mysql://localhost:3306/booking-and-review-db

#config for kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true