server.port=8084
#config for spring data jpa
spring.datasource.url=jdbc:mysql://localhost:3306/notification-db

# kafka consumer config
spring.kafka.consumer.group-id=notification-group-v2
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
# Disable header check to deserialize JSON directly to local DTO without package name matching
spring.kafka.producer.properties.spring.json.add.type.headers=false